configuration:
  pageTitle: "Catatan PWK ITB"
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics: null
  locale: "id-ID"
  baseUrl: "menatasappk.github.io/catatan-pl"
  ignorePatterns: [".obsidian", ".trash", "__series__"]
  defaultDateType: "created"
  generateFrontmatter: true
  theme:
    fontOrigin: "googleFonts"
    cdnCaching: true
    typography:
      header: "Schibsted Grotesk"
      body: "Source Sans Pro"
      code: "IBM Plex Mono"
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
        textHighlight: "#fff2cc"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
        textHighlight: "#b33a3a"
plugins:
  transformers:
    - FrontMatter:
    - CreatedModifiedDate:
        priority: ["frontmatter", "filesystem"]
    - SyntaxHighlighting:
        theme:
          light: "github-light"
          dark: "github-dark"
    - ObsidianFlavoredMarkdown:
        enableInHtmlEmbed: false
    - GitHubFlavoredMarkdown:
    - TableOfContents:
    - CrawlLinks:
        markdownLinkResolution: "shortest"
    - Description:
    - Latex:
        renderEngine: "katex"
  filters:
    - RemoveDrafts:
  emitters:
    - AliasRedirects:
    - ComponentResources:
    - ContentPage:
    - FolderPage:
    - TagPage:
    - ContentIndex:
        enableSiteMap: true
        enableRSS: true
    - Assets:
    - Static:
    - NotFoundPage:
