configuration:
  pageTitle: "Catatan PWK ITB"
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics: null
  locale: "id-ID"
  baseUrl: "menatasappk.github.io/catatan-pl"
  ignorePatterns: [".obsidian", ".trash", "__series__"]
  defaultDateType: "created"
  generateFrontmatter: true
  theme:
    fontOrigin: "googleFonts"
    cdnCaching: true
    typography:
      header: "Lora"
      body: "Inter"
      code: "Fira Code"
    colors:
      lightMode:
        light: "#fbf9f4"
        lightgray: "#e5e0d8"
        gray: "#8c857b"
        darkgray: "#2d312e"
        dark: "#3a5040"
        secondary: "#4a6b53"
        tertiary: "#c87d55"
        highlight: "rgba(74, 107, 83, 0.08)"
        textHighlight: "#fff2cc"
      darkMode:
        light: "#161917"
        lightgray: "#242926"
        gray: "#67726a"
        darkgray: "#e3e7e4"
        dark: "#8cb899"
        secondary: "#70a280"
        tertiary: "#dd9569"
        highlight: "rgba(112, 162, 128, 0.1)"
        textHighlight: "#b33a3a"
plugins:
  transformers:
    - FrontMatter:
    - CreatedModifiedDate:
        priority: ["frontmatter", "filesystem"]
    - SyntaxHighlighting:
        theme:
          light: "github-light"
          dark: "github-dark"
    - ObsidianFlavoredMarkdown:
        enableInHtmlEmbed: false
    - GitHubFlavoredMarkdown:
    - TableOfContents:
    - CrawlLinks:
        markdownLinkResolution: "shortest"
    - Description:
    - Latex:
        renderEngine: "katex"
  filters:
    - RemoveDrafts:
  emitters:
    - AliasRedirects:
    - ComponentResources:
    - ContentPage:
    - FolderPage:
    - TagPage:
    - ContentIndex:
        enableSiteMap: true
        enableRSS: true
    - Assets:
    - Static:
    - NotFoundPage:
